---
- name: debug a list
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:

    - name: loop
      debug:
        msg:
          - "name is {{ item.name }}"
          - "ip is {{ item.ip }}"
      loop: "{{ networks }}"
      vars:
        networks:
          - name: foo
            ip: bar
